export const GET_COUNTRIES = "GET_COUNTRIES";
export const COUNTRIES_SEARCH = "COUNTRIES_SEARCH";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const SORT_COUNTRIES = "SORT_COUNTRIES";
export const SET_SORT_BY = "SET_SORT_BY";





